//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIPIT_9
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oboryds
    {
        public int Id { get; set; }
        public string Model_oboryd { get; set; }
        public string Firma_oboryd { get; set; }
    }
}
