//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIPIT_9
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rabors
    {
        public int Id { get; set; }
        public int ID_oboryd { get; set; }
        public int ID_vid_rabot { get; set; }
        public System.DateTime Data_polychen { get; set; }
        public System.DateTime Data_vipolnen { get; set; }
    }
}
