//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIPIT_9
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rabot
    {
        public int Id { get; set; }
        public Nullable<int> ID_oboryd { get; set; }
        public Nullable<int> ID_vid_rabot { get; set; }
        public Nullable<System.DateTime> Data_polychen { get; set; }
        public Nullable<System.DateTime> Data_vipolnen { get; set; }
    
        public virtual Oboryd Oboryd { get; set; }
        public virtual Vid_rabot Vid_rabot { get; set; }
    }
}
